[package]
name = "test-alloc"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
clap.workspace = true
indicatif = { version = "0.17.11", features = [
  "in_memory",
  "improved_unicode",
] }
rand = { version = "0.9.1", features = ["simd_support"] }
